blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ DiscussÃµes
    url: https://github.com/BeroLab/beroboard/discussions
    about: Para perguntas e discussÃµes gerais sobre o projeto
  - name: ğŸ“š DocumentaÃ§Ã£o
    url: https://github.com/BeroLab/beroboard/wiki
    about: Confira nossa documentaÃ§Ã£o antes de abrir uma issue